pipeline {
    agent { label 'kube' }
    parameters {
        string(name: 'hello')
        string(name: 'hi')
        string(name: 'hola')
        string(name: 'BUILD_VERSION')
    }  
    stages {
        stage('Stage-1') {
            steps {
              echo "Hello World"
              echo "Build_version = $BUILD_VERSION"                
            }
            post {
                success {
                    echo "Successful saying hello"
                    script {
                        manager.addShortText("$buildNumber")
                    }                    
                }
            }
        }
        stage('Stage-2-Input') {
            options {
                timeout(time: 10, unit: 'SECONDS') 
            }
            input {
                message "Proceed to Stage-2?"
            }            
            steps {
                echo "Finished Stage-2-Input"
            }
            post {
                always {
                    sh '''
                    echo "BUILD_VERSION=$buildNumber" > pipelineConfig.txt
                    '''                    
                    stash includes: 'pipelineConfig.txt', name: 'pipelineConfig'
                    script {
                        manager.addShortText("$buildNumber")
                    }
                }            
            }
        }
        stage('Stage-2') {
            steps {
                sh '''
                echo "Hello, time to do something"
                uname -a
                cat hello.txt | sed "s/{{ HELLO_WORLD }}/${hello}/g" | sed "s/{{ HI_WORLD }}/${hi}/g" | sed "s/{{ HOLA_WORLD }}/${hola}/g"
                '''            
                echo "Build_version = $BUILD_VERSION"
            }
            post {
                success {
                    echo "Successful do something"
                    script {
                        manager.addShortText("$buildNumber")
                    }
                }               
            }
        }
        stage('Stage-3-Input') {
            options {
                timeout(time: 10, unit: 'SECONDS') 
            }
            input {
                message "Proceed to Stage-2?"
            }            
            steps {
                echo "Finished Stage-2-Input"
            }
            post {
                always {
                    sh '''
                    echo "BUILD_VERSION=$buildNumber" > pipelineConfig.txt
                    '''                    
                    stash includes: 'pipelineConfig.txt', name: 'pipelineConfig'
                    script {
                        manager.addShortText("$buildNumber")
                    }
                }            
            }
        }        
        stage('Stage-3') {
            steps {
                unstash 'pipelineConfig'   
                sh '''
                export $(grep -v '^#' pipelineConfig.txt | xargs)
                '''
                echo "Build_version = $BUILD_VERSION"
                sh "ls -la"
            }
            post {
                success {
                    echo "Successful ended"
                    script {
                        manager.addShortText("$buildNumber")
                    }                    
                }
                always {
                    sh '''
                    echo "BUILD_VERSION=$buildNumber" > pipelineConfig.txt
                    '''                    
                    stash includes: 'pipelineConfig.txt', name: 'pipelineConfig'
                }                 
            }
        }      
    }
}
